
a = 'Exception in thread Thread-2:\nTraceback (most recent call last):\n  File "/usr/local/lib/python2.7/threading.py", line 808, in __bootstrap_inner\n    self.run()\n  File "/usr/local/lib/python2.7/threading.py", line 761, in run\n    self.__target(*self.__args, **self.__kwargs)\n  File "/home/mahongchao/env_ktrove/lib/python2.7/site-packages/trove/taskmanager/engine/flow.py", line 545, in _call_sub_task\n    res = self._call_task_fn(args)\n  File "/home/mahongchao/env_ktrove/lib/python2.7/site-packages/trove/taskmanager/engine/flow.py", line 569, in _call_task_fn\n    return self.task_fn(**args_map)\n  File "/home/mahongchao/env_ktrove/lib/python2.7/site-packages/trove/taskmanager/tasks/network.py", line 342, in change_vip_to_basic\n    dettach_vip(instance_info.id)\n  File "/home/mahongchao/env_ktrove/lib/python2.7/site-packages/trove/taskmanager/tasks/network.py", line 289, in dettach_vip\n    raise Exception(msg)\nException: Failed release_vip with vip:904a92aa-d83f-415a-86c5-cda2301b52f3, exception:Entity \'<class \'trove.db.data_models.product.DBProduct\'>\' has no property \'context\'\n\nException in thread Thread-1:\nTraceback (most recent call last):\n  File "/usr/local/lib/python2.7/threading.py", line 808, in __bootstrap_inner\n    self.run()\n  File "/usr/local/lib/python2.7/threading.py", line 761, in run\n    self.__target(*self.__args, **self.__kwargs)\n  File "/home/mahongchao/env_ktrove/lib/python2.7/site-packages/trove/taskmanager/engine/flow.py", line 393, in run\n    self._run(flow_id, args)\n  File "/home/mahongchao/env_ktrove/lib/python2.7/site-packages/trove/taskmanager/engine/flow.py", line 428, in _run\n    res = self._call_sub_tasks(db_info.id, call_args)\n  File "/home/mahongchao/env_ktrove/lib/python2.7/site-packages/trove/taskmanager/engine/flow.py", line 514, in _call_sub_tasks\n    raise FlowError("sub task:{} failed, msg:{}".format(sub_task.id, sub_task.result))\nFlowError: sub task:61526106-82f9-4ba3-add1-748d8ae58792 failed, msg:Failed release_vip with vip:904a92aa-d83f-415a-86c5-cda2301b52f3, exception:Entity \'<class \'trove.db.data_models.product.DBProduct\'>\' has no property \'context\'\n\n'

print a